#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Mar 11 12:40:54 CST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 132f060917924e08a182bea93a6aa71f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot InstrMem_tb_behav xil_defaultlib.InstrMem_tb -log elaborate.log"
xelab -wto 132f060917924e08a182bea93a6aa71f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot InstrMem_tb_behav xil_defaultlib.InstrMem_tb -log elaborate.log

