#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Mar 11 13:17:16 CST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim DataMem_tb_behav -key {Behavioral:sim_1:Functional:DataMem_tb} -tclbatch DataMem_tb.tcl -view /home/kam/dev/school/computer_architecture_645/fpga/HW05_MIPS_MEM_Bielawski/DataMem/simulation_sources/DataMem_wave.wcfg -log simulate.log"
xsim DataMem_tb_behav -key {Behavioral:sim_1:Functional:DataMem_tb} -tclbatch DataMem_tb.tcl -view /home/kam/dev/school/computer_architecture_645/fpga/HW05_MIPS_MEM_Bielawski/DataMem/simulation_sources/DataMem_wave.wcfg -log simulate.log

