set_property SRC_FILE_INFO {cfile:/home/kam/dev/school/computer_architecture_645/fpga/constraints/switchToLED_A7csg324_constraints.xdc rfile:../../../../constraints/switchToLED_A7csg324_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports switch]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports led]
