@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Feb 02 17:45:47 -0600 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto c0e9c0c0e58d4a91986eb8ca26d29413 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot n_bit_up_down_counter_tb_behav xil_defaultlib.n_bit_up_down_counter_tb -log elaborate.log"
call xelab  -wto c0e9c0c0e58d4a91986eb8ca26d29413 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot n_bit_up_down_counter_tb_behav xil_defaultlib.n_bit_up_down_counter_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
