@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Feb 02 17:45:52 -0600 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim n_bit_up_down_counter_tb_behav -key {Behavioral:sim_1:Functional:n_bit_up_down_counter_tb} -tclbatch n_bit_up_down_counter_tb.tcl -view C:/Users/e190a104/Documents/00_VSim_InClass_Tutorial/n_bit_up_down_counter_Solution/simulation_sources/n_bit_up_down_counter_wave.wcfg -log simulate.log"
call xsim  n_bit_up_down_counter_tb_behav -key {Behavioral:sim_1:Functional:n_bit_up_down_counter_tb} -tclbatch n_bit_up_down_counter_tb.tcl -view C:/Users/e190a104/Documents/00_VSim_InClass_Tutorial/n_bit_up_down_counter_Solution/simulation_sources/n_bit_up_down_counter_wave.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
