#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 15 08:51:01 CST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim mod_m_up_dn_count_tb_behav -key {Behavioral:sim_1:Functional:mod_m_up_dn_count_tb} -tclbatch mod_m_up_dn_count_tb.tcl -view /home/kam/dev/school/computer_architecture_645/fpga/HW02_Type_Mismatch/mod_m_up_dn_count/simulation_sources/mod_m_up_dn_count_wave.wcfg -log simulate.log"
xsim mod_m_up_dn_count_tb_behav -key {Behavioral:sim_1:Functional:mod_m_up_dn_count_tb} -tclbatch mod_m_up_dn_count_tb.tcl -view /home/kam/dev/school/computer_architecture_645/fpga/HW02_Type_Mismatch/mod_m_up_dn_count/simulation_sources/mod_m_up_dn_count_wave.wcfg -log simulate.log

