#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Apr 19 15:45:33 CDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim cu_tb_behav -key {Behavioral:sim_1:Functional:cu_tb} -tclbatch cu_tb.tcl -view /home/kam/dev/school/computer_architecture_645/fpga/HW09_MIPS_CU_Bielawski/simulation_sources/cu_wave.wcfg -log simulate.log"
xsim cu_tb_behav -key {Behavioral:sim_1:Functional:cu_tb} -tclbatch cu_tb.tcl -view /home/kam/dev/school/computer_architecture_645/fpga/HW09_MIPS_CU_Bielawski/simulation_sources/cu_wave.wcfg -log simulate.log

