webtalk_init -webtalk_dir /home/kam/dev/school/computer_architecture_645/fpga/HW09_MIPS_CU_Bielawski/MIPS_CU/MIPS_CU.sim/sim_1/behav/xsim/xsim.dir/cu_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 19 15:54:35 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8bdd082f-2f1a-42e6-8995-68a0cc5a7de7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "555e0205de2e4f348bbd50bbf0992f75" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "989.267 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "400 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "123536_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3193382613 -regid "" -xml /home/kam/dev/school/computer_architecture_645/fpga/HW09_MIPS_CU_Bielawski/MIPS_CU/MIPS_CU.sim/sim_1/behav/xsim/xsim.dir/cu_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/kam/dev/school/computer_architecture_645/fpga/HW09_MIPS_CU_Bielawski/MIPS_CU/MIPS_CU.sim/sim_1/behav/xsim/xsim.dir/cu_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/kam/dev/school/computer_architecture_645/fpga/HW09_MIPS_CU_Bielawski/MIPS_CU/MIPS_CU.sim/sim_1/behav/xsim/xsim.dir/cu_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
